"""Update models with relationships and timestamps

Revision ID: 369a28339860
Revises: d6496de82e05
Create Date: 2024-07-25 10:57:18.790442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369a28339860'
down_revision = 'd6496de82e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('course', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('enrollment', sa.Column('enrolled_at', sa.DateTime(), nullable=True))
    op.add_column('resource', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('resource', 'created_at')
    op.drop_column('enrollment', 'enrolled_at')
    op.drop_column('course', 'created_at')
    op.drop_column('assignment', 'created_at')
    # ### end Alembic commands ###
