"""Add Assignment model

Revision ID: d6496de82e05
Revises: 51f61c744f10
Create Date: 2024-07-25 10:44:18.285921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6496de82e05'
down_revision = '51f61c744f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('course', 'pdf_resources')
    op.drop_column('course', 'video_resources')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('video_resources', sa.TEXT(), nullable=True))
    op.add_column('course', sa.Column('pdf_resources', sa.TEXT(), nullable=True))
    op.drop_table('assignment')
    # ### end Alembic commands ###
